# 워크플로 이름: GitHub Actions 탭에서 표시될 이름
name: Terraform Apply

# on: 이 워크플로를 실행할 조건(트리거) 정의
on:
    push:
        branches: [main] # main 브랜치에 push 될 때만 실행

# permissions: 이 워크플로에 부여할 GitHub 토큰 권한
permissions:
    id-token: write #OIDC 토큰 발급 허용. (AWS 인증에 필요)
    contents: read # 레포 코드를 읽을 수 있는  권한

jobs:
    plan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ap-northeast-2

            - uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.7.0"

            - name: Terraform Init
              run: |
                cd envs/dev
                terraform init

            - name: Terraform Validate
              run: |
                cd envs/dev
                terraform validate

            # -out=tfplan: 플랜 결과를 파일로 저장 (apply 시 동일한 플랜 사용)
            - name: Terraform Plan
              run: |
                cd envs/dev
                terraform plan -out=tfplan

            # plan 파일을 apply job에서 사용할 수 있도록 artifact로 업로드
            - name: Upload Plan
              uses: actions/upload-artifact@v4
              with:
                name: tfplan
                path: envs/dev/tfplan

    apply:
        runs-on: ubuntu-latest
        needs: plan # plan job이 성공해야 실행
        environment: production # 이 환경에 설정된 Required Reviewers가 승인해야 실행

        steps:
            - uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ap-northeast-2

            - uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.7.0"

            # plan job에서 저장한 플랜 파일 다운로드
            - name: Download Plan
              uses: actions/download-artifact@v4
              with:
                name: tfplan
                path: envs/dev

            # apply job은 새 Runner이므로 init 재실행 필요
            - name: Terraform Init
              run: |
                cd envs/dev
                terraform init

            # 저장된 플랜 파일로 apply (plan 시점과 동일한 변경만 적용)
            - name: Terraform Apply
              run: |
                cd envs/dev
                terraform apply -auto-approve tfplan
